# Generated by Django 4.2.6 on 2023-10-15 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('username', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('languages', models.TextField()),
                ('skills', models.TextField()),
                ('state', models.CharField(max_length=100)),
                ('interests', models.TextField()),
            ],
        ),
    ]
