# Generated by Django 4.2.6 on 2023-10-16 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userData', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Students',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('username', models.CharField(max_length=100, unique=True)),
                ('email', models.EmailField(max_length=254)),
                ('languages', models.TextField()),
                ('skills', models.TextField()),
                ('state', models.CharField(max_length=100)),
                ('interests', models.TextField()),
            ],
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
