/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { InputType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import { EnumUserEducation } from "./EnumUserEducation";
import { IsEnum, IsOptional, IsString } from "class-validator";
import { EnumUserLanguages } from "./EnumUserLanguages";
import { IsJSONValue } from "@app/custom-validators";
import { GraphQLJSON } from "graphql-type-json";
import { InputJsonValue } from "../../types";
import { EnumUserSkills } from "./EnumUserSkills";

@InputType()
class UserUpdateInput {
  @ApiProperty({
    required: false,
    enum: EnumUserEducation,
    isArray: true,
  })
  @IsEnum(EnumUserEducation, {
    each: true,
  })
  @IsOptional()
  @Field(() => [EnumUserEducation], {
    nullable: true,
  })
  education?: Array<"Btech">;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  firstName?: string | null;

  @ApiProperty({
    required: false,
    enum: EnumUserLanguages,
    isArray: true,
  })
  @IsEnum(EnumUserLanguages, {
    each: true,
  })
  @IsOptional()
  @Field(() => [EnumUserLanguages], {
    nullable: true,
  })
  languages?: Array<"Hindi">;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  lastName?: string | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  password?: string;

  @ApiProperty({
    required: false,
  })
  @IsJSONValue()
  @IsOptional()
  @Field(() => GraphQLJSON, {
    nullable: true,
  })
  roles?: InputJsonValue;

  @ApiProperty({
    required: false,
    enum: EnumUserSkills,
    isArray: true,
  })
  @IsEnum(EnumUserSkills, {
    each: true,
  })
  @IsOptional()
  @Field(() => [EnumUserSkills], {
    nullable: true,
  })
  skills?: Array<"Skills">;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  state?: string | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  username?: string;
}

export { UserUpdateInput as UserUpdateInput };
